/*! project-name v0.0.1 | (c) 2022 YOUR NAME | MIT License | http://link-to-your-git-repo.com */
const illustrationsInfo = [
  {
    community:'cerro-de-leones',
    cloudsCommunity:{distance:185, direction:'-'},
    animalsCommunity:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    animalsDistance:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    animalsSolution:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    sourceTypeDistance: 'river',
    numberOfBirdsDistance:2,
    directionBirdsDistance:'right',
    numberOfBirdsSolution:2,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:85, direction:'+', rotationWheelBack:496, rotationWheelFront:653},
    missedSchoolHours:{min:12, max:15},
    hasTwoSchools:true,
    waterContaminants:{biological:7, inorganic:6}
  },
  {
    community:'las-mercedes-km11',
    cloudsCommunity:{distance:78, direction:'-'},
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'cow', selector:''}, {id:'chicken', selector:''}],
    sourceTypeDistance: 'canal',
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:3,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:60, direction:'+', rotationWheelBack:814, rotationWheelFront:814},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:5}
  },
  {
    community:'la-merced',
    cloudsCommunity:{distance:242, direction:'-'},
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    sourceTypeDistance: 'canal',
    numberOfBirdsDistance:2,
    directionBirdsDistance:'right',
    numberOfBirdsSolution:0,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:125, direction:'+', rotationWheelBack:1435, rotationWheelFront:1435},
    vehicleSolution:{distance:100, direction:'-', rotationWheelBack:1115, rotationWheelFront:1465},
    missedSchoolHours:{min:4, max:7},
    hasTwoSchools:true,
    waterContaminants:{biological:6, inorganic:3}
  },
  {
    community:'totoral-bajo',
    cloudsCommunity:{distance:280, direction:'-'},
    animalsCommunity:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsDistance:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    animalsSolution:[{id:'chicken1', selector:''}, {id:'chicken2', selector:''}],
    sourceTypeDistance: 'canal',
    numberOfBirdsDistance:4,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:1,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:80, direction:'-', rotationWheelBack:467, rotationWheelFront:614},
    vehicleSolution:{distance:90, direction:'-', rotationWheelBack:1005, rotationWheelFront:1315},
    missedSchoolHours:{min:8, max:11},
    hasTwoSchools:true,
    waterContaminants:{biological:7, inorganic:3}
  },
  {
    community:'las-mercedes',
    cloudsCommunity:{distance:30, direction:'+'},
    animalsCommunity:[{id:'cow1', selector:''}, {id:'cow2', selector:''}],
    animalsDistance:[{id:'cow1', selector:''}, {id:'cow2', selector:''}],
    animalsSolution:[{id:'chicken', selector:''}, {id:'cow', selector:''}],
    sourceTypeDistance: 'canal',
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:2,
    directionBirdsSolution:'right',
    vehicleCommunity:{distance:270, direction:'-', rotationWheelBack:1577, rotationWheelFront:2074},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:2}
  },
  {
    community:'totoral-alto',
    cloudsCommunity:{distance:75, direction:'-'},
    animalsCommunity:[{id:'cow', selector:''}],
    animalsDistance:[{id:'cow', selector:''}],
    animalsSolution:[{id:'cow', selector:''}],
    sourceTypeDistance: 'canal',
    numberOfBirdsDistance:0,
    directionBirdsDistance:'',
    numberOfBirdsSolution:3,
    directionBirdsSolution:'left',
    vehicleCommunity:{distance:130, direction:'+', rotationWheelBack:1492, rotationWheelFront:1492},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:7, inorganic:3}
  },
  {
    community:'carrizalillo',
    cloudsCommunity:{distance:200, direction:'-'},
    animalsCommunity:[{id:'cow', selector:''}],
    animalsDistance:[{id:'cow', selector:''}],
    animalsSolution:[{id:'cow', selector:''}],
    sourceTypeDistance: '',
    numberOfBirdsDistance:2,
    directionBirdsDistance:'left',
    numberOfBirdsSolution:0,
    directionBirdsSolution:'',
    vehicleCommunity:{distance:106, direction:'-', rotationWheelBack:1438, rotationWheelFront:1438},
    vehicleSolution:{distance:100, direction:'-', rotationWheelBack:1115, rotationWheelFront:1465},
    missedSchoolHours:{min:3, max:3},
    hasTwoSchools:false,
    waterContaminants:{biological:6, inorganic:5}
  }
];